// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuDu79nYD28vecuNCaa77-7dDDu5YHmDQ',
    appId: '1:937055748879:web:b60bc08a4f539db626747a',
    messagingSenderId: '937055748879',
    projectId: 'finalproject-bd0c7',
    authDomain: 'finalproject-bd0c7.firebaseapp.com',
    storageBucket: 'finalproject-bd0c7.firebasestorage.app',
    measurementId: 'G-5QQ8Y7KMDH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9Hm0MK6C38YqEZl2TX7MQgN0jHnRGlLk',
    appId: '1:937055748879:android:1ec807e1176744bc26747a',
    messagingSenderId: '937055748879',
    projectId: 'finalproject-bd0c7',
    storageBucket: 'finalproject-bd0c7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDR7O8Am16OcMhOtG9-WNBjP0JG9qXXJDg',
    appId: '1:937055748879:ios:f50ae74cb89f42e126747a',
    messagingSenderId: '937055748879',
    projectId: 'finalproject-bd0c7',
    storageBucket: 'finalproject-bd0c7.firebasestorage.app',
    iosBundleId: 'com.example.finalproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDR7O8Am16OcMhOtG9-WNBjP0JG9qXXJDg',
    appId: '1:937055748879:ios:f50ae74cb89f42e126747a',
    messagingSenderId: '937055748879',
    projectId: 'finalproject-bd0c7',
    storageBucket: 'finalproject-bd0c7.firebasestorage.app',
    iosBundleId: 'com.example.finalproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuDu79nYD28vecuNCaa77-7dDDu5YHmDQ',
    appId: '1:937055748879:web:1362f5001e10592426747a',
    messagingSenderId: '937055748879',
    projectId: 'finalproject-bd0c7',
    authDomain: 'finalproject-bd0c7.firebaseapp.com',
    storageBucket: 'finalproject-bd0c7.firebasestorage.app',
    measurementId: 'G-9WLMWL2HSS',
  );
}
